### ISSUE TITLE
error when writing xml path for path with colon

### ISSUE THREAD

**Issue by jprokos** [mborsetti/webchanges#31]
Not sure it's a bug in me or the software.

I have a job:

```
name: 21_SwimSwam News - Time Standard
url: "https://swimswam.com/feed/#1"
filter:
   - xpath:
      method: xml
      path: '//item/title/text()|//item/description/text()'
      exclude: 'a'
   - html2text:
      method: bs4
   - keep_lines_containing:
      re: '(?i)usa\sswimming|time\sstandard|ruta'
   - re.sub: '(?m)^[ \t]*'
additions_only: true
```

According to the docs I should be able to add this line to the path but I get an error.

`//item/content:encoded/text()`
`path: '//item/title/text()|//item/description/text()|//item/content:encoded/text()'`

https://webchanges.readthedocs.io/en/stable/filters.html?highlight=RSS#using-css-and-xpath-filters-with-xml-and-exclusions

Seems I am having an issue with the colon.

**Comment by mborsetti** [comment]
Hmmm... Its Either YAML or some legacy code; I'll look into it.

Can you please run the job with '--verbose' and paste at least the top lines (with version and system info) and the full traceback and error message?

**Comment by jprokos** [comment]
That was it... thanks for pointing me in the right direction.

working job below:

```
name: 21_SwimSwam News - Time Standard
url: "https://swimswam.com/feed/#1"
filter:
   - xpath:
      method: xml
      path: '//item/title/text()//item/description/text()|//item/content:encoded/text()'
      namespaces:
        content: http://purl.org/rss/1.0/modules/content/
      exclude: 'a'
   - keep_lines_containing:
      re: '(?i)usa\sswimming|time\sstandard'
   - html2text: re
additions_only: true
```
