### ISSUE TITLE
Trouble with csv2text filter

### ISSUE THREAD

**Issue by jprokos** [mborsetti/webchanges#35]
I played around with the different options available but am unable to get results without key errors using this link:

https://www.swimmingrank.com/zone/central/zone_meet_4_girls_13_14.csv

It's possible it's just a malformed csv

```
name: 33_SwimRank - Zones 13-14
url: "https://www.swimmingrank.com/zone/central/zone_meet_4_girls_13_14.csv"
filter:
  - csv2text:
      format_message: test {swimmer}
      has_header: false
```

> 1-zsh% webchanges --test 33
> Traceback (most recent call last):
>   File "/Users/john/.pyenv/versions/3.10.3/bin/webchanges", line 8, in <module>
>     sys.exit(main())
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/cli.py", line 237, in main
>     urlwatch_command.run()
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/command.py", line 712, in run
>     self.handle_actions()
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/command.py", line 646, in handle_actions
>     self.test_job(self.urlwatch_config.test_job)
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/command.py", line 212, in test_job
>     raise job_state.exception
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/handler.py", line 160, in process
>     filtered_data = FilterBase.process(filter_kind, subfilter, self, filtered_data)
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/filters.py", line 239, in process
>     return filtercls(job_state.job, job_state).filter(data, subfilter)
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/filters.py", line 560, in filter
>     lines.append(message.format(*i))
> KeyError: 'swimmer'

```
name: 33_SwimRank - Zones 13-14
url: "https://www.swimmingrank.com/zone/central/zone_meet_4_girls_13_14.csv"
filter:
  - csv2text:
      format_message: test {0}
      has_header: false
```

> 1-zsh% webchanges --test 33
> Traceback (most recent call last):
>   File "/Users/john/.pyenv/versions/3.10.3/bin/webchanges", line 8, in <module>
>     sys.exit(main())
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/cli.py", line 237, in main
>     urlwatch_command.run()
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/command.py", line 712, in run
>     self.handle_actions()
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/command.py", line 646, in handle_actions
>     self.test_job(self.urlwatch_config.test_job)
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/command.py", line 212, in test_job
>     raise job_state.exception
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/handler.py", line 160, in process
>     filtered_data = FilterBase.process(filter_kind, subfilter, self, filtered_data)
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/filters.py", line 239, in process
>     return filtercls(job_state.job, job_state).filter(data, subfilter)
>   File "/Users/john/.pyenv/versions/3.10.3/lib/python3.10/site-packages/webchanges/filters.py", line 558, in filter
>     lines.append(message.format(**legend))
> IndexError: Replacement index 0 out of range for positional args tuple
