### ISSUE TITLE
Documentation for diff

### ISSUE THREAD

**Issue by jprokos** [mborsetti/webchanges#36]
I believe the example should be:

report:
  html:
     diff: table

```
 SyntaxWarning: Unrecognized directive(s) in the configuration file /Users/john/Library/Preferences/webchanges/config.yaml:
report:
  text:
    diff: table
Check for typos (documentation at https://webchanges.readthedocs.io/)
```
