### ISSUE TITLE
[FEATURE] Method to load and see changes on a modal

### ISSUE THREAD

**Issue by ghost** [mborsetti/webchanges#41]
**Is your feature request related to a problem? Please describe.**
Having an issue with a particular page that requires javascript, and have tried using "use_browser" to no avail. I think it's because the page uses a modal

https://www.teamunify.com/team/ilpac/page/calendar#/team-events/upcoming/1359396

**Describe the solution you'd like**
I would like to monitor changes on this page

**Describe alternatives you've considered**

```
name: 34_PAC Meets
url: "https://www.teamunify.com/team/ilpac/page/calendar#/team-events/upcoming/1359396"
use_browser: true
filter:
  - xpath:
      path: "//div[contains(@class,"modal-content")]"
  - html2text:
```

```
name: 34_PAC Meets
url: "https://www.teamunify.com/team/ilpac/page/calendar#/team-events/upcoming/1359396"
use_browser: true
filter:
  - html2text:
```

**Additional context**
