### ISSUE TITLE
[BUG] saved snapshots not effective, job cycles

### ISSUE THREAD

**Issue by jprokos** [mborsetti/webchanges#43]
**Describe the bug**
Not sure a bug but maybe a clarification is needed on functionality...

I have a job that for some reason gets triggered over and over after an initial change.

```
--- #### RealVNC.com - working 4/10/22 ####
name: 04_RealVNC Server
url: "https://www.realvnc.com/en/connect/download/vnc/macos/"
filter:
  - xpath:
      path: '(//a[contains(@href,"MacOSX-x86_64.pkg")])'
  - html2text:
      method: html2text
additions_only: true
compared_versions: 2
```
The notifications are via email and they show that the href link has changed. This rotates between two states on every call after the initial change:

> https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-6.10.1-MacOSX-x86_64.pkg
> https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-6.10.0-MacOSX-x86_64.pkg
> https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-6.10.1-MacOSX-x86_64.pkg
>...

**Version info**
 - webchanges: 3.10.3 Copyright 2020- Mike Borsetti
 - CPython: 3.10.5 ('main', 'Jul 28 2022 16:48:00') Clang 13.1.6 (clang-1316.0.21.2.5)
 - System: macOS-12.5-x86_64-i386-64bit

**Additional context**
Calling webchanges with  `--max-snapshots 2` versus the default of 4 doesn't seem to have any effect
Adding `compared_versions: 2` to the job doesn't seem to have any effect (initially was not set, set to troubleshoot)
Adding `additions_only: true` to the job doesn't seem to have any effect

**Questions**
Once `--max_snapshots` is set is it permanent? If not, may we set `--max_snaphots` in the `.config.yaml` file for all jobs?

I'd be happy to add any additional info
