### ISSUE TITLE
[BUG] `--errors` report error while normal run performs fine

### ISSUE THREAD

**Issue by yubiuser** [mborsetti/webchanges#88]
I run `webchanges` once a day vai cron job with `--errors` to ... check for errors. There is one particular job that regularly reports (always the same) error, but during the normal run nothing sticks out. I tried to run it with `--errors` from cli but it performs fine. 
Is there any difference when a job is executed vs when it runs via `--errors`? I particular, does a normal job try to fetch more than once in case an connection error occurs?

Would it make sense to offer a "file" reporter? I could image to run `--errors` and log a verbose output to a file but still send a notification to a chosen reporter (e.g. with a hint to check the logs). Like `webchanges -v --errors mail --errorfile error.log ....` 
____

The job is

```
name: "Xenia Downloads"
url: "https://www.xenia-espresso.de/downloads/"
headers:
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
filter:
    - element-by-class: media-body
    - html2text:
       body_width: 0
       ignore_links: true
       ignore_images: true
       single-line-break: true
    - execute: paste -s -d' \n'
    - execute: paste -s -d' \n'
    - execute: awk 'BEGIN { FS = "__" } ; { print $1 $3 }'
    - strip
``` 

Reported error is 

```
Error "[Errno-3] Try again": Xenia Downloads...
```

**Version info.**
```
Software:
• webchanges: 3.26.0
• CPython: 3.12.7 ('main', 'Nov 12 2024 02:17:58') GCC 13.2.1 20240309
• SQLite: 3.45.3

Installed PyPi dependencies:
• cryptography: 43.0.3
```
